### ISSUE TITLE
consider more accessible colors?

### ISSUE THREAD

**Issue by knksmith57** [lrlna/pino-colada#19]
Heya, first off _thank you_ for this awesome tool and contribution to the pino ecosystem!

This formatter made it easy and fun to remove the conditional pretty-printing logic from our app in favor of pure, pluggable, ndjson output. Excellent idea and much appreciated contribution.

To the crux of this issue: I'd like to propose dropping `dim` modifiers from log statements to make the output more accessible. Dim red for error statements is particularly troubling and is the main change I'll champion here.

Totally understand that there are a lot of host environment settings that play into the rendering of these things. The demo screenshot in the README is _beautiful_ and, while I couldn't figure out what terminal theme was used when capturing it, I took the following screenshots to highlight renderings in iTerm2 w/ default dark theme and Hyperterm with the top 2-most downloaded themes ([pokemon](https://www.npmjs.com/package/hyper-pokemon) and [solarized-dark](https://www.npmjs.com/package/hyper-solarized-dark))

Using this script to generate the output: https://gist.github.com/knksmith57/7b673fe77429534a93f2c7ea5ff61c20

1. iTerm2 default dark theme:
<img width="1092" alt="iterm2-default-dark" src="https://user-images.githubusercontent.com/796851/28233865-4c97a02c-68b7-11e7-957f-89bf95830e9e.png">

2. Hyperterm default theme: 
<img width="695" alt="hyperterm-default" src="https://user-images.githubusercontent.com/796851/28233874-65a133b2-68b7-11e7-8234-5c0a7f3ef776.png">

3. Hyperterm solarized-dark theme:
<img width="685" alt="hyperterm-solarized-dark" src="https://user-images.githubusercontent.com/796851/28233883-7b2d3afa-68b7-11e7-8931-ef613776af94.png">

4. Hyperterm pokemon theme w/ pikachu:
<img width="686" alt="hyperterm-pokemon-pikachu" src="https://user-images.githubusercontent.com/796851/28233888-8bd6a42c-68b7-11e7-9100-4187dfa0bdc7.png">

5. Hyperterm pokemon theme w/ gengar:
<img width="680" alt="hyperterm-pokemon-gengar" src="https://user-images.githubusercontent.com/796851/28233896-98e9e1ba-68b7-11e7-818d-8cfe69a1825d.png">

What do you think?

Thanks again!

**Comment by knksmith57** [comment]
forgot to mention: it may be worth noting that the v minimal pretty parser that ships w/ pino [uses standard colors](https://github.com/pinojs/pino/blob/3e309d3add/pretty.js#L74-L82).

Obviously this tool is much more beautiful and fun and has a better name but I thought it might be worth linking to 😃

**Comment by lrlna** [comment]
hey @knksmith57, I am all for getting rid of `dim` version of things to make it a bit easier to read.


I am thinking a way of making this more accessible would be to allow users to pass on their choice of colours? I feel like there are so many terminal themes people work with that it'd be p impossible to cover them all. I am going to need to think about it a bit more tho, cause that would require an `opts` object most likely, and I am a bit iffy about that. Give me a day or two tho!

I did read over the pino codebase quite extensively when making this. This is another tool in the ecosystem, so I think there is room for a standard colour version of things, or something like this (or whatever else people like)

**Comment by sebdeckers** [comment]
Sorry to dig up an old bike shedding thread.

> I am thinking a way of making this more accessible would be to allow users to pass on their choice of colours? I feel like there are so many terminal themes people work with that it'd be p impossible to cover them all.

Agreed, but the main usability issue here is dimming rather than colour. FWIW I think the default colours are pretty. They just lack contrast.

**Comment by lrlna** [comment]
all right, dimming has been removed in #20. Hopefully it makes it a bit easier for y'all.
