### ISSUE TITLE
How to use in fastify

### ISSUE THREAD

**Issue by KidkArolis** [lrlna/pino-colada#27]
Hi,

I got so confused when reading through pino, pino-pretty, pino-colada docs...

I tried this:

```js
const app = fastify({
  logger: {
    level: 'info',
    prettifier: require('pino-colada')
  }
})
```

with no luck.. And I really don't want to do the `|` thing.. I just want the app to print the pretty logs. Is that possible?

**Comment by mcollina** [comment]
It's definitely possible, check out https://github.com/fastify/fastify-cli/blob/master/start.js#L146-L152.
