### ISSUE TITLE
output more info

### ISSUE THREAD

**Issue by yoshuawuyts** [lrlna/pino-colada#3]
[server-sink](https://github.com/yoshuawuyts/server-sink) produces a whole bunch of info besides `message`. I think it'd be good to output more data, akin to how `garnish` operates

```txt
{ name: 'http',
  message: 'request',
  method: 'GET',
  remoteAddress: '::1',
  url: '/' }
{ name: 'http',
  message: 'response',
  method: 'GET',
  url: '/',
  statusCode: 200,
  elapsed: 55,
  contentLength: 242 }
```
![garnish image](https://camo.githubusercontent.com/218d3d4087bc44f8453f5f5d8ef8a78eb1519169/687474703a2f2f692e696d6775722e636f6d2f507675733876792e706e67)

**Comment by lrlna** [comment]
totes agree :v:

**Comment by lrlna** [comment]
@yoshuawuyts hmmmm is `contentLength` the bundle size? and `elapsed` the time it took to load the bundle? want to double check.

**Comment by yoshuawuyts** [comment]
Yeah it is
