### ISSUE TITLE
stream.on is not a function

### ISSUE THREAD

**Issue by Eomm** [lrlna/pino-colada#34]
Hi,
in fastify-cli we have a report of this error with the v1.6.0 release:

To reproduce:

```
npx fastify-cli generate pretty
cd pretty/
npm i
// edit the package.json adding "-P" flag in the start script
npm start 
// now we have the error

// to solve:
npm ls pino-colada
// you should see 1.6.0

// installing previous version works:
npm i pino-colada@1.5.1
npm start
// all works fine
```

There are some fixes we should apply to our code base?
We use pino-colada here:
https://github.com/fastify/fastify-cli/blob/b6e7caba7e8f2644f5243f9d94902faacfbda886/start.js#L98-L102

Thanks

The stack trace:

```
  stream.on('close', function () {
         ^
TypeError: stream.on is not a function
    at destroyer (C:\Users\behem\workspaceFastify\asd\boooom\node_modules\pump\index.js:26:10)
    at C:\Users\behem\workspaceFastify\asd\boooom\node_modules\pump\index.js:70:12
    at Array.map (<anonymous>)
    at pump (C:\Users\behem\workspaceFastify\asd\boooom\node_modules\pump\index.js:67:26)
    at runFastify (C:\Users\behem\workspaceFastify\asd\boooom\node_modules\fastify-cli\start.js:101:5)
    at start (C:\Users\behem\workspaceFastify\asd\boooom\node_modules\fastify-cli\start.js:50:10)
```

Original issue ref: https://github.com/fastify/fastify-cli/issues/235

**Comment by lrlna** [comment]
Hey! Thanks for reporting this. I accidentally published a breaking change in 1.6.0. 1.6.0 has now been deprecated. With the way you use it in fastify-cli, please keep using `1.5.1`. Really sorry this broke things for you.

**Comment by mcollina** [comment]
Can you unpublish 1.6.0 or publish 1.5.1 as 1.6.1? Thanks

**Comment by lrlna** [comment]
@mcollina npm didn't let me unpublish, i did try on friday.

Therefore, I've published 1.5.1 as 1.6.1. Let me know if something is off. Hopefully that means you don't have to lock it anymore!

**Comment by pc3b3r** [comment]
I confirm, it's working fine, tried right now.

**Comment by Eomm** [comment]
Thank you for your support!
