### ISSUE TITLE
Programmatic use doesn't work properly

### ISSUE THREAD

**Issue by rijkvanzanten** [lrlna/pino-colada#37]
When using `pino-colada` programmatically as per the docs:

```js
const pino = require('pino')
const logger = pino({
  prettifier: require('pino-colada')
})

logger.info('hi')
```

Nothing happens. When I add `prettyPrint` to the options it starts working:

```js
const pino = require('pino')
const logger = pino({
  prettyPrint: {},
  prettifier: require('pino-colada')
})

logger.info('hi')
```

... but only for the first log line. All others after that are the default "raw" JSON

**Comment by rijkvanzanten** [comment]
False alarm! I'm a dummy 🙈 

I forgot to hook up express-pino-logger to the same Pino instance, so it would only prettify the non-express logs 🤦

**Comment by lrlna** [comment]
Glad it sorted itself out ^__^

**Comment by MartijnHols** [comment]
Ah indeed the programmatic use in the readme is missing the prettyPrint. It doesn't work without it, even when using the correct logger in express-pino-logger. Thanks for pointing that out.
