### ISSUE TITLE
prettyPrint is deprecated 

### ISSUE THREAD

**Issue by MuhammadAbbasAkhtar** [lrlna/pino-colada#45]
Change `prettifier`  to `customPrettifiers` in the readme

**Comment by TheTechmage** [comment]
I couldn't find where prettifier had been renamed to customPrettifiers anywhere in the pino docs. The closest thing that I could find was this https://github.com/pinojs/pino/pull/1249 but they appear to just be removing it entirely in those commits.

**Comment by lrlna** [comment]
`pretty-print` and `prettifier` are still part of the [pino documentation](https://github.com/pinojs/pino/blob/master/docs/pretty.md#api-example). We will therefore keep it in ours.
